#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Outpu\OutputInterface;
use Dotenv\Dotenv;

require 'vendor/autoload.php';
$dotenv = new Dotenv(__DIR__);
$dotenv->load();
$app = new Application('NFL Analysis command utility','1.0');

$app->add(new Mox\Commands\WeatherCommand());
$app->add(new Mox\Commands\NFLTeamsCommand());
$app->add(new Mox\Commands\ByesCommand());
$app->add(new Mox\Commands\ScheduleCommand());
$app->add(new Mox\Commands\Players\PlayersCommand());
$app->add(new Mox\Commands\Players\PositionQBCommand());
$app->add(new Mox\Commands\Players\PositionRBCommand());
$app->add(new Mox\Commands\Players\PositionWRCommand());
$app->add(new Mox\Commands\Players\PositionTECommand());
$app->add(new Mox\Commands\Players\PositionKCommand());
$app->add(new Mox\Commands\Players\PositionDEFCommand());
$app->add(new Mox\Commands\Players\TiersCommand());
$app->add(new Mox\Commands\AuctionValuesCommand());
$app->add(new Mox\Commands\Draft\RankingsCommand());
$app->add(new Mox\Commands\Draft\ProjectionsQBCommand());
$app->add(new Mox\Commands\Draft\ProjectionsRBCommand());
$app->add(new Mox\Commands\Draft\ProjectionsWRCommand());
$app->add(new Mox\Commands\Draft\ProjectionsTECommand());
$app->add(new Mox\Commands\Draft\ProjectionsKCommand());
$app->add(new Mox\Commands\Draft\ProjectionsDEFCommand());
$app->add(new Mox\Commands\Draft\ProjectionsIDPCommand());
$app->add(new Mox\Commands\Rankings\WeeklyQBCommand());
$app->add(new Mox\Commands\Rankings\WeeklyWRCommand());
$app->add(new Mox\Commands\Rankings\WeeklyRBCommand());
$app->add(new Mox\Commands\Rankings\WeeklyTECommand());
$app->add(new Mox\Commands\Rankings\WeeklyKCommand());
$app->add(new Mox\Commands\Rankings\WeeklyDEFCommand());
$app->add(new Mox\Commands\Projections\WeeklyQBCommand());
$app->add(new Mox\Commands\Projections\WeeklyRBCommand());
$app->add(new Mox\Commands\Projections\WeeklyWRCommand());
$app->add(new Mox\Commands\Projections\WeeklyTECommand());
$app->add(new Mox\Commands\Projections\WeeklyKCommand());
$app->add(new Mox\Commands\Projections\WeeklyDEFCommand());

$app->run();
